@host = http://localhost:5000

###Login
post {{host}}/api/auth/login
content-type: application/json

{
  "username": "adam",
  "password": "adam"
}

###Brand brw add
POST {{host}}/api/brand/brw
content-type: application/json

{
  "brand": "BH30",
  "hop_std": "YES",
  "hop_crft": "YES",
  "hop_dry": "YES",
  "supr_sac": "YES",
  "type": "YES",
  "note": "Hello"
}

###Brand brw get
GET {{host}}/api/brand/brw/BH40

###Brand brw Patch
PATCH {{host}}/api/brand/brw/BH40
content-type: application/json

{
  "hop_std": "No",
  "hop_crft": "No",
  "hop_dry": "No",
  "supr_sac": "No",
  "type": "No",
  "note": "No Note"
}

###Brand brw delete
DELETE {{host}}/api/brand/brw/BH40

###Brand fin add
POST {{host}}/api/brand/fin
content-type: application/json

{
  "brand": "HBUD",
  "brw_id": "BH50",
  "note": "fin note"
}

###Brand fin get
GET {{host}}/api/brand/fin/HBUD

###Brand fin Patch
PATCH {{host}}/api/brand/fin/HBUD
content-type: application/json

{
  "brw_id": "BH50",
  "note": "old fin note"
}

###Brand fin delete
DELETE {{host}}/api/brand/fin/HBUD

###Brand pck add
POST {{host}}/api/brand/pck
content-type: application/json

{
  "brand": "BUD5",
  "fin_id": "HBUD",
  "note": "pck note"
}